# Generated by Django 5.1.2 on 2026-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_add_id_jour_to_indisponibilites'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='joueurs',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], default='fr', max_length=2),
        ),
    ]
